//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentID { get; set; }
        public string IncidentTitle { get; set; }
        public byte[] IncidentDescription { get; set; }
        public Nullable<System.DateTime> IncidentCreationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> UrgencyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Status Status { get; set; }
        public virtual Urgency Urgency { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
