//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Urgency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urgency()
        {
            this.Incidents = new HashSet<Incident>();
        }
    
        public int UrgencyID { get; set; }
        [Required(ErrorMessage = "Necesario")]
        [DataType(DataType.Text)]
        [Display(Name = "Nombre")]
        public string UrgencyName { get; set; }
        [Required(ErrorMessage = "Necesario")]
        [DataType(DataType.Text)]
        [Display(Name = "Descripcion")]
        public string UrgencyDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
    }
}
