//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Incidents = new HashSet<Incident>();
            this.Incidents1 = new HashSet<Incident>();
        }
    
        public int UserID { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string UserEmail { get; set; }
        [Required]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name = "Ultima Actividad")]
        public string UserLastActivity { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public System.DateTime UserBirthday { get; set; }
        public int ProfileID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents1 { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
